# Generated by Django 4.1.2 on 2022-11-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BizBoglanishUchunModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_uzb', models.CharField(default='', max_length=60, verbose_name='Manzil(Uzbek)')),
                ('location_ru', models.CharField(default='', max_length=60, verbose_name='Manzil(Ruscha)')),
                ('location_eng', models.CharField(default='', max_length=60, verbose_name='Manzil(English)')),
                ('phone_number', models.CharField(default='', max_length=12, verbose_name='Telefon nomeri')),
                ('email', models.EmailField(default='', max_length=60, verbose_name='Email')),
                ('telegram_link', models.CharField(default='', max_length=12, verbose_name='Telegram link')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BizningGalereyamiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=90, verbose_name='Rasm nomi')),
                ('image_file', models.ImageField(upload_to='bizning_galeryamiz/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BizningLogistikaRasmlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='images', max_length=90, verbose_name='Rasm nomi')),
                ('image_file', models.ImageField(upload_to='bizning_logistika_rasmlari/')),
            ],
        ),
        migrations.CreateModel(
            name='BizningMuzeylar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uzb', models.CharField(default='', max_length=90, verbose_name="O'zbekcha nomi")),
                ('name_ru', models.CharField(default='', max_length=90, verbose_name='Ruscha nomi')),
                ('name_eng', models.CharField(default='', max_length=90, verbose_name='Inglizcha nomi')),
                ('title_uzb', models.TextField(default='', max_length=2500, verbose_name='haqida malimot kirting(Uzb)')),
                ('title_ru', models.TextField(default='', max_length=2500, verbose_name='haqida malimot kirting(Rus)')),
                ('title_eng', models.TextField(default='', max_length=2500, verbose_name='haqida malimot kirting(Eng)')),
                ('image_file', models.ImageField(upload_to='bizning_muzeyimiz/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BizningRestoranlarniRasmlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='images', max_length=90, verbose_name='Rasm nomi')),
                ('image_file', models.ImageField(upload_to='bizning_restaranlari_rasmlari/')),
            ],
        ),
        migrations.CreateModel(
            name='BizningSavdoMarkazlarniRasmlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='images', max_length=90, verbose_name='Rasm nomi')),
                ('image_file', models.ImageField(upload_to='bizning_savdo_markazlar_rasmlari/')),
            ],
        ),
        migrations.CreateModel(
            name='BoglanishModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60, verbose_name='Ismi')),
                ('phone_number', models.CharField(default='', max_length=12, verbose_name='Telefon nomeri')),
                ('email', models.EmailField(default='', max_length=60, verbose_name='Email')),
                ('message', models.CharField(default='', max_length=12, verbose_name='Qoldirilgan xabar')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KorgazmalarRasmlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='images', max_length=90, verbose_name='Rasm nomi')),
                ('image_file', models.ImageField(upload_to='bizning_korgazmalar_rasmlari/')),
            ],
        ),
        migrations.CreateModel(
            name='LogistikaTurlarimiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uzb', models.CharField(default='', max_length=90, verbose_name="Logistika Turi O'zbekcha nomi")),
                ('name_ru', models.CharField(default='', max_length=90, verbose_name='Logistika Turi Ruscha nomi')),
                ('name_eng', models.CharField(default='', max_length=90, verbose_name='Logistika Turi Inglizcha nomi')),
                ('title_uzb', models.TextField(default='', max_length=2500, verbose_name='Logistika Turi haqida malimot kirting(Uzb)')),
                ('title_ru', models.TextField(default='', max_length=2500, verbose_name='Logistika Turi haqida malimot kirting(Rus)')),
                ('title_eng', models.TextField(default='', max_length=2500, verbose_name='Logistika Turii haqida malimot kirting(Eng)')),
                ('image_file', models.ImageField(upload_to='lagistika_turi_rasmlari/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafarTurizmRasmlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uzb', models.CharField(default='', max_length=90, verbose_name="O'zbekcha nomi")),
                ('name_ru', models.CharField(default='', max_length=90, verbose_name='Ruscha nomi')),
                ('name_eng', models.CharField(default='', max_length=90, verbose_name='Inglizcha nomi')),
                ('title_uzb', models.CharField(default='', max_length=90, verbose_name="O'zbekcha haqida malimot")),
                ('title_ru', models.CharField(default='', max_length=90, verbose_name='Ruscha haqida malimot')),
                ('title_eng', models.CharField(default='', max_length=90, verbose_name='Inglizcha haqida malimot')),
                ('image_file', models.ImageField(upload_to='tarixiy_turizm_rasmlari/', verbose_name='Rasm faylni kirting')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TarixiyTurizmRasmlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uzb', models.CharField(default='', max_length=90, verbose_name="O'zbekcha nomi")),
                ('name_ru', models.CharField(default='', max_length=90, verbose_name='Ruscha nomi')),
                ('name_eng', models.CharField(default='', max_length=90, verbose_name='Inglizcha nomi')),
                ('title_uzb', models.CharField(default='', max_length=90, verbose_name="O'zbekcha haqida malimot")),
                ('title_ru', models.CharField(default='', max_length=90, verbose_name='Ruscha haqida malimot')),
                ('title_eng', models.CharField(default='', max_length=90, verbose_name='Inglizcha haqida malimot')),
                ('image_file', models.ImageField(upload_to='tarixiy_turizm_rasmlari/', verbose_name='Rasm faylni kirting')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TurizmTurlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uzb', models.CharField(default='', max_length=90, verbose_name="Turizm turi O'zbekcha nomi")),
                ('name_ru', models.CharField(default='', max_length=90, verbose_name='Turizm turi Ruscha nomi')),
                ('name_eng', models.CharField(default='', max_length=90, verbose_name='Turizm turi Inglizcha nomi')),
                ('title_uzb', models.TextField(default='', max_length=2500, verbose_name='Turizm turi haqida malimot kirting(Uzb)')),
                ('title_ru', models.TextField(default='', max_length=2500, verbose_name='Turizm turi haqida malimot kirting(Rus)')),
                ('title_eng', models.TextField(default='', max_length=2500, verbose_name='Turizm turi haqida malimot kirting(Eng)')),
                ('image_file', models.ImageField(upload_to='turizm_turlari_rasmlar/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xodimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=190, verbose_name='F.I.SH')),
                ('degree', models.CharField(default='', max_length=190, verbose_name='Lavozim')),
                ('phone_number', models.CharField(default='', max_length=190, verbose_name='Telefon raqami')),
                ('email', models.EmailField(default='', max_length=190, verbose_name='Elektron pochta manzil')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YangiliklarRasmlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='images', max_length=90, verbose_name='Rasm nomi')),
                ('image_file', models.ImageField(upload_to='yangilkilar_images/', verbose_name='Rasm filesni')),
            ],
        ),
        migrations.CreateModel(
            name='YangiliklarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uzb', models.CharField(default='', max_length=900, verbose_name='Yangilik nomi (uzbek)')),
                ('name_ru', models.CharField(default='', max_length=900, verbose_name='Yangilik nomi (ruscha)')),
                ('name_eng', models.CharField(default='', max_length=900, verbose_name='Yangilik nomi (english)')),
                ('title_uzb', models.TextField(default='', max_length=5500, verbose_name='Yangilik haqida (uzbek)')),
                ('title_ru', models.TextField(default='', max_length=5500, verbose_name='Yangilik haqida (ruscha)')),
                ('title_eng', models.TextField(default='', max_length=5500, verbose_name='Yangilik haqida (english)')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image_file', models.ManyToManyField(related_name='imagefile', to='api.yangiliklarrasmlari', verbose_name='Yangilikar haqida  rasm kirting')),
            ],
        ),
        migrations.CreateModel(
            name='BizningSavdoMarkazlarhaqida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uzb', models.TextField(default='', max_length=2500, verbose_name='Savdo Markaz haqida malimot kirting(Uzb)')),
                ('title_ru', models.TextField(default='', max_length=2500, verbose_name='Savdo Markaz haqida malimot kirting(Rus)')),
                ('title_eng', models.TextField(default='', max_length=2500, verbose_name='Savdo Markaz haqida malimot kirting(Eng)')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image_file', models.ManyToManyField(related_name='imagefile', to='api.bizningsavdomarkazlarnirasmlari', verbose_name='Savdo Markaz haqida rasm kirting')),
            ],
        ),
        migrations.CreateModel(
            name='BizningRestoranlarhaqida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uzb', models.TextField(default='', max_length=2500, verbose_name='Restoranlar haqida malimot kirting(Uzb)')),
                ('title_ru', models.TextField(default='', max_length=2500, verbose_name='Restoranlar haqida malimot kirting(Rus)')),
                ('title_eng', models.TextField(default='', max_length=2500, verbose_name='Restoranlar haqida malimot kirting(Eng)')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image_file', models.ManyToManyField(related_name='imagefilerestaurant', to='api.bizningrestoranlarnirasmlari', verbose_name='Restoranlar haqida rasm kirting')),
            ],
        ),
    ]
