# Generated by Django 4.1.2 on 2022-10-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bizboglanishuchunmodel',
            name='location_eng',
            field=models.CharField(default='', max_length=60, verbose_name='Manzil(English)'),
        ),
        migrations.AlterField(
            model_name='bizboglanishuchunmodel',
            name='location_ru',
            field=models.CharField(default='', max_length=60, verbose_name='Manzil(Ruscha)'),
        ),
    ]
