# Generated by Django 4.1.2 on 2022-10-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurizmTurlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uzb', models.CharField(default='', max_length=90, verbose_name="Turizm turi O'zbekcha nomi")),
                ('name_ru', models.CharField(default='', max_length=90, verbose_name='Turizm turi Ruscha nomi')),
                ('name_eng', models.CharField(default='', max_length=90, verbose_name='Turizm turi Inglizcha nomi')),
                ('title_uzb', models.CharField(default='', max_length=2500, verbose_name='Turizm turi haqida malimot kirting(Uzb)')),
                ('title_ru', models.CharField(default='', max_length=2500, verbose_name='Turizm turi haqida malimot kirting(Rus)')),
                ('title_eng', models.CharField(default='', max_length=2500, verbose_name='Turizm turi haqida malimot kirting(Eng)')),
                ('image_file', models.ImageField(upload_to='turizm_turlari_rasmlar/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TurizTurlari',
        ),
    ]
