# Generated by Django 4.1.2 on 2022-11-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bizboglanishuchunmodel_location_eng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafarTurizmRasmlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uzb', models.CharField(default='', max_length=90, verbose_name="O'zbekcha nomi")),
                ('name_ru', models.CharField(default='', max_length=90, verbose_name='Ruscha nomi')),
                ('name_eng', models.CharField(default='', max_length=90, verbose_name='Inglizcha nomi')),
                ('title_uzb', models.CharField(default='', max_length=90, verbose_name="O'zbekcha haqida malimot")),
                ('title_ru', models.CharField(default='', max_length=90, verbose_name='Ruscha haqida malimot')),
                ('title_eng', models.CharField(default='', max_length=90, verbose_name='Inglizcha haqida malimot')),
                ('image_file', models.ImageField(upload_to='tarixiy_turizm_rasmlari/', verbose_name='Rasm faylni kirting')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='tarixiyturizmrasmlari',
            name='title_eng',
            field=models.CharField(default='', max_length=90, verbose_name='Inglizcha haqida malimot'),
        ),
        migrations.AddField(
            model_name='tarixiyturizmrasmlari',
            name='title_ru',
            field=models.CharField(default='', max_length=90, verbose_name='Ruscha haqida malimot'),
        ),
        migrations.AddField(
            model_name='tarixiyturizmrasmlari',
            name='title_uzb',
            field=models.CharField(default='', max_length=90, verbose_name="O'zbekcha haqida malimot"),
        ),
    ]
