# Generated by Django 4.1.2 on 2022-10-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_turizmturlari_delete_turizturlari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bizningmuzeylar',
            name='title_eng',
            field=models.TextField(default='', max_length=2500, verbose_name='haqida malimot kirting(Eng)'),
        ),
        migrations.AlterField(
            model_name='bizningmuzeylar',
            name='title_ru',
            field=models.TextField(default='', max_length=2500, verbose_name='haqida malimot kirting(Rus)'),
        ),
        migrations.AlterField(
            model_name='bizningmuzeylar',
            name='title_uzb',
            field=models.TextField(default='', max_length=2500, verbose_name='haqida malimot kirting(Uzb)'),
        ),
        migrations.AlterField(
            model_name='bizningrestoranlarhaqida',
            name='title_eng',
            field=models.TextField(default='', max_length=2500, verbose_name='Restoranlar haqida malimot kirting(Eng)'),
        ),
        migrations.AlterField(
            model_name='bizningrestoranlarhaqida',
            name='title_ru',
            field=models.TextField(default='', max_length=2500, verbose_name='Restoranlar haqida malimot kirting(Rus)'),
        ),
        migrations.AlterField(
            model_name='bizningrestoranlarhaqida',
            name='title_uzb',
            field=models.TextField(default='', max_length=2500, verbose_name='Restoranlar haqida malimot kirting(Uzb)'),
        ),
        migrations.AlterField(
            model_name='bizningsavdomarkazlarhaqida',
            name='title_eng',
            field=models.TextField(default='', max_length=2500, verbose_name='Savdo Markaz haqida malimot kirting(Eng)'),
        ),
        migrations.AlterField(
            model_name='bizningsavdomarkazlarhaqida',
            name='title_ru',
            field=models.TextField(default='', max_length=2500, verbose_name='Savdo Markaz haqida malimot kirting(Rus)'),
        ),
        migrations.AlterField(
            model_name='bizningsavdomarkazlarhaqida',
            name='title_uzb',
            field=models.TextField(default='', max_length=2500, verbose_name='Savdo Markaz haqida malimot kirting(Uzb)'),
        ),
        migrations.AlterField(
            model_name='logistikaturlarimiz',
            name='title_eng',
            field=models.TextField(default='', max_length=2500, verbose_name='Logistika Turii haqida malimot kirting(Eng)'),
        ),
        migrations.AlterField(
            model_name='logistikaturlarimiz',
            name='title_ru',
            field=models.TextField(default='', max_length=2500, verbose_name='Logistika Turi haqida malimot kirting(Rus)'),
        ),
        migrations.AlterField(
            model_name='logistikaturlarimiz',
            name='title_uzb',
            field=models.TextField(default='', max_length=2500, verbose_name='Logistika Turi haqida malimot kirting(Uzb)'),
        ),
        migrations.AlterField(
            model_name='turizmturlari',
            name='title_eng',
            field=models.TextField(default='', max_length=2500, verbose_name='Turizm turi haqida malimot kirting(Eng)'),
        ),
        migrations.AlterField(
            model_name='turizmturlari',
            name='title_ru',
            field=models.TextField(default='', max_length=2500, verbose_name='Turizm turi haqida malimot kirting(Rus)'),
        ),
        migrations.AlterField(
            model_name='turizmturlari',
            name='title_uzb',
            field=models.TextField(default='', max_length=2500, verbose_name='Turizm turi haqida malimot kirting(Uzb)'),
        ),
    ]
