# Generated by Django 4.1.2 on 2022-12-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_safarturizmrasmlari_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HammaSahifadaChiqadiganRasmlarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uzb', models.CharField(default='', max_length=90, verbose_name=" O'zbekcha nomi")),
                ('title_uzb', models.TextField(default='', max_length=2500, verbose_name=' haqida malimot kirting(Uzb)')),
                ('title_ru', models.TextField(default='', max_length=2500, verbose_name=' haqida malimot kirting(Rus)')),
                ('title_eng', models.TextField(default='', max_length=2500, verbose_name=' haqida malimot kirting(Eng)')),
                ('image_file', models.ImageField(upload_to='hamma_sahifada_chiqadigan_rasmlar_model/', verbose_name='Rasm filesni')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
