# Generated by Django 4.1.2 on 2022-11-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(default='', max_length=30, verbose_name='About pagega chiqadigan rasm nomi')),
                ('photo_file', models.ImageField(upload_to='about_image/', verbose_name='About pagega chiqadigan rasm files')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, verbose_name='Foydalanuvchi nomi')),
                ('email', models.EmailField(default='', max_length=150, verbose_name='Foydalanuvchi email')),
                ('phone_nomer', models.IntegerField(blank=True, default=0, verbose_name='Foydalanuvchi  telefon nomeri')),
                ('message', models.CharField(default='', max_length=1000, verbose_name='Foydalanuvchi yuborgan xabar')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelLocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(default='', max_length=150, verbose_name='Nomi')),
                ('hotel_location', models.CharField(default='', max_length=150, verbose_name='Joylashgan Hudud')),
                ('hotel_phone', models.IntegerField(blank=True, default=0, verbose_name='Telefon nomeri')),
                ('hotel_email', models.EmailField(blank=True, default=0, max_length=254, verbose_name='email')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_room_image', models.ImageField(upload_to='hotel_room_image/', verbose_name='Mehmon xona rasm')),
                ('hotel_room_name', models.CharField(max_length=100, verbose_name='Mehmonxona nomi')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('meal_title', models.CharField(max_length=100, verbose_name='haqida malimot')),
                ('meal_price', models.FloatField(verbose_name='Narxi')),
                ('catagorya', models.CharField(max_length=100, verbose_name='Ovaqt turini kirting')),
                ('meal_image', models.ImageField(default='meal_image/meal.jpg', null=True, upload_to='meal_image/', verbose_name='Ovaqt rasm')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenAndCloseHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_hour', models.TimeField(verbose_name='Mehmonhonani ochilish vaqti')),
                ('close_hour', models.TimeField(verbose_name='Mehmonhonani yopilish vaqti')),
                ('opan_close_day', models.CharField(default='Monday to Friday', max_length=70, verbose_name='Mehmonhonani ishlash kunlari')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=250, verbose_name='Xonani nomi')),
                ('room_title', models.CharField(max_length=1000, verbose_name='Xonani haqida malimot')),
                ('room_price', models.FloatField(verbose_name='Xonani narxi')),
                ('room_file', models.ImageField(upload_to='room_image/', verbose_name='Xonani rasmi')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=10000, verbose_name="About Pageda chiqadigan ma'limot")),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('photo_files', models.ManyToManyField(blank=True, related_name='photo_files', to='mehmonxona.aboutimages', verbose_name='About Pagega chiqadigan rasmlarni tanlang')),
            ],
        ),
    ]
