# Generated by Django 4.1.2 on 2022-10-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehmonxona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealmodel',
            name='catagorya',
            field=models.CharField(max_length=100, verbose_name='Ovaqt turini kirting'),
        ),
    ]
