# Generated by Django 4.1.2 on 2022-10-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehmonxona', '0002_alter_mealmodel_catagorya'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealmodel',
            name='meal_image',
            field=models.ImageField(default='meal_image/meal.jpg', null=True, upload_to='meal_image/', verbose_name='Ovaqt rasm'),
        ),
    ]
